BEGIN
    CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMER (
        CUSTID VARCHAR(50),
        NAME VARCHAR(255),
        EMAILID VARCHAR(255),
        REGION VARCHAR(100),
        LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    );

    CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD."order" (
        ORDERID VARCHAR(50),
        CUSTID VARCHAR(50),
        ITEMNAME VARCHAR(255),
        PRICEPERUNIT NUMBER(18,2),
        QTY NUMBER(10,0),
        ORDER_DATE DATE,
        STARTDATE DATE,
        ENDDATE DATE,
        ISACTIVE VARCHAR(10),
        LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    );

    CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ERROR_LOG (
        LOG_ID NUMBER AUTOINCREMENT,
        PROCEDURE_NAME VARCHAR(255),
        ERROR_MESSAGE VARCHAR(4000),
        ERROR_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    );

    RETURN 'Tables created successfully';
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;