BEGIN
    CREATE FILE FORMAT IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CSV_FORMAT
        TYPE = 'CSV'
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        SKIP_HEADER = 1
        NULL_IF = ('NULL', 'null', '')
        EMPTY_FIELD_AS_NULL = TRUE
        ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

    RETURN 'File formats created successfully';
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;