BEGIN
    -- Truncate staging area before fresh load
    TRUNCATE TABLE IF EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMER;

    COPY INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMER (CUSTID, NAME, EMAILID, REGION)
    FROM @GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD_STAGE/customerdata
    FILE_FORMAT = (
        TYPE = 'CSV'
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        SKIP_HEADER = 1
        NULL_IF = ('NULL', 'null', '')
        EMPTY_FIELD_AS_NULL = TRUE
        ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    )
    ON_ERROR = CONTINUE;

    RETURN 'Customer data loaded successfully';
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ERROR_LOG (PROCEDURE_NAME, ERROR_MESSAGE)
        VALUES ('LOAD_CUSTOMER_DATA', SQLERRM);
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;