BEGIN
    -- Truncate staging area before fresh load
    TRUNCATE TABLE IF EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD."order";

    COPY INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD."order" (ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE)
    FROM @GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD_STAGE/orderdata
    FILE_FORMAT = (
        TYPE = 'CSV'
        FIELD_OPTIONALLY_ENCLOSED_BY = '"'
        SKIP_HEADER = 1
        NULL_IF = ('NULL', 'null', '')
        EMPTY_FIELD_AS_NULL = TRUE
        ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    )
    ON_ERROR = CONTINUE;

    RETURN 'Order data loaded successfully';
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ERROR_LOG (PROCEDURE_NAME, ERROR_MESSAGE)
        VALUES ('LOAD_ORDER_DATA', SQLERRM);
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;