BEGIN
    -- Remove null records (where CUSTID is null)
    DELETE FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMER
    WHERE CUSTID IS NULL;

    -- Remove duplicates keeping the latest loaded record
    CREATE OR REPLACE TEMPORARY TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMER_DEDUP AS
    SELECT CUSTID, NAME, EMAILID, REGION, LOAD_TIMESTAMP
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMER
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CUSTID ORDER BY LOAD_TIMESTAMP DESC) = 1;

    TRUNCATE TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMER;

    INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMER (CUSTID, NAME, EMAILID, REGION, LOAD_TIMESTAMP)
    SELECT CUSTID, NAME, EMAILID, REGION, LOAD_TIMESTAMP
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMER_DEDUP;

    RETURN 'Customer validation and deduplication completed successfully';
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ERROR_LOG (PROCEDURE_NAME, ERROR_MESSAGE)
        VALUES ('VALIDATE_DEDUP_CUSTOMER', SQLERRM);
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;