BEGIN
    -- Remove null records (where ORDERID or CUSTID is null)
    DELETE FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD."order"
    WHERE ORDERID IS NULL OR CUSTID IS NULL;

    -- Remove duplicates keeping the latest loaded record
    CREATE OR REPLACE TEMPORARY TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ORDER_DEDUP AS
    SELECT ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE, LOAD_TIMESTAMP
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD."order"
    QUALIFY ROW_NUMBER() OVER (PARTITION BY ORDERID ORDER BY LOAD_TIMESTAMP DESC) = 1;

    TRUNCATE TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD."order";

    INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD."order" (ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE, LOAD_TIMESTAMP)
    SELECT ORDERID, CUSTID, ITEMNAME, PRICEPERUNIT, QTY, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE, LOAD_TIMESTAMP
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ORDER_DEDUP;

    RETURN 'Order validation and deduplication completed successfully';
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ERROR_LOG (PROCEDURE_NAME, ERROR_MESSAGE)
        VALUES ('VALIDATE_DEDUP_ORDER', SQLERRM);
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;