BEGIN
    CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ORDERSUMMARY (
        ORDERSUMMARY_KEY NUMBER AUTOINCREMENT,
        ORDERID VARCHAR(50),
        CUSTID VARCHAR(50),
        NAME VARCHAR(255),
        EMAILID VARCHAR(255),
        REGION VARCHAR(100),
        ITEMNAME VARCHAR(255),
        PRICEPERUNIT NUMBER(18,2),
        QTY NUMBER(10,0),
        TOTALAMOUNT NUMBER(18,2),
        ORDER_DATE DATE,
        STARTDATE DATE,
        ENDDATE DATE,
        ISACTIVE VARCHAR(10),
        IS_CURRENT BOOLEAN DEFAULT TRUE,
        EFFECTIVE_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        EFFECTIVE_TO TIMESTAMP_NTZ DEFAULT '9999-12-31 00:00:00',
        LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    );

    RETURN 'Ordersummary table created successfully';
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;