BEGIN
    CREATE TABLE IF NOT EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMER_SCD2 (
        CUSTOMER_SCD2_KEY NUMBER AUTOINCREMENT,
        CUSTID VARCHAR(50),
        NAME VARCHAR(255),
        EMAILID VARCHAR(255),
        REGION VARCHAR(100),
        IS_CURRENT BOOLEAN DEFAULT TRUE,
        EFFECTIVE_FROM TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
        EFFECTIVE_TO TIMESTAMP_NTZ DEFAULT '9999-12-31 00:00:00',
        LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
    );

    RETURN 'Customer SCD2 table created successfully';
EXCEPTION
    WHEN OTHER THEN
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;