BEGIN
    -- Create a staging view with joined customer and order data
    CREATE OR REPLACE TEMPORARY TABLE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ORDERSUMMARY_STG AS
    SELECT
        O.ORDERID,
        C.CUSTID,
        C.NAME,
        C.EMAILID,
        C.REGION,
        O.ITEMNAME,
        O.PRICEPERUNIT,
        O.QTY,
        (O.PRICEPERUNIT * O.QTY) AS TOTALAMOUNT,
        O.ORDER_DATE,
        O.STARTDATE,
        O.ENDDATE,
        O.ISACTIVE
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD."order" O
    INNER JOIN GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMER C
        ON O.CUSTID = C.CUSTID;

    -- SCD Type 2: Expire existing records where customer data has changed
    UPDATE GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ORDERSUMMARY TGT
    SET
        IS_CURRENT = FALSE,
        EFFECTIVE_TO = CURRENT_TIMESTAMP()
    WHERE TGT.IS_CURRENT = TRUE
    AND EXISTS (
        SELECT 1
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ORDERSUMMARY_STG STG
        WHERE STG.ORDERID = TGT.ORDERID
        AND STG.CUSTID = TGT.CUSTID
        AND (
            STG.NAME != TGT.NAME
            OR STG.EMAILID != TGT.EMAILID
            OR STG.REGION != TGT.REGION
            OR STG.ITEMNAME != TGT.ITEMNAME
            OR STG.PRICEPERUNIT != TGT.PRICEPERUNIT
            OR STG.QTY != TGT.QTY
            OR STG.TOTALAMOUNT != TGT.TOTALAMOUNT
        )
    );

    -- Insert new records (changed records and brand new records)
    INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ORDERSUMMARY (
        ORDERID, CUSTID, NAME, EMAILID, REGION, ITEMNAME, PRICEPERUNIT, QTY,
        TOTALAMOUNT, ORDER_DATE, STARTDATE, ENDDATE, ISACTIVE,
        IS_CURRENT, EFFECTIVE_FROM, EFFECTIVE_TO, LOAD_TIMESTAMP
    )
    SELECT
        STG.ORDERID,
        STG.CUSTID,
        STG.NAME,
        STG.EMAILID,
        STG.REGION,
        STG.ITEMNAME,
        STG.PRICEPERUNIT,
        STG.QTY,
        STG.TOTALAMOUNT,
        STG.ORDER_DATE,
        STG.STARTDATE,
        STG.ENDDATE,
        STG.ISACTIVE,
        TRUE AS IS_CURRENT,
        CURRENT_TIMESTAMP() AS EFFECTIVE_FROM,
        '9999-12-31 00:00:00'::TIMESTAMP_NTZ AS EFFECTIVE_TO,
        CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ORDERSUMMARY_STG STG
    WHERE NOT EXISTS (
        SELECT 1
        FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ORDERSUMMARY TGT
        WHERE TGT.ORDERID = STG.ORDERID
        AND TGT.CUSTID = STG.CUSTID
        AND TGT.IS_CURRENT = TRUE
        AND TGT.NAME = STG.NAME
        AND TGT.EMAILID = STG.EMAILID
        AND TGT.REGION = STG.REGION
        AND TGT.ITEMNAME = STG.ITEMNAME
        AND TGT.PRICEPERUNIT = STG.PRICEPERUNIT
        AND TGT.QTY = STG.QTY
        AND TGT.TOTALAMOUNT = STG.TOTALAMOUNT
    );

    RETURN 'Ordersummary SCD2 load completed successfully';
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ERROR_LOG (PROCEDURE_NAME, ERROR_MESSAGE)
        VALUES ('LOAD_ORDERSUMMARY_SCD2', SQLERRM);
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;