BEGIN
    -- Truncate and reload aggregated data
    TRUNCATE TABLE IF EXISTS GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMERAGGREGATESPEND;

    INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.CUSTOMERAGGREGATESPEND (NAME, ORDER_DATE, TOTAL_SPEND, LOAD_TIMESTAMP)
    SELECT
        NAME,
        ORDER_DATE,
        SUM(TOTALAMOUNT) AS TOTAL_SPEND,
        CURRENT_TIMESTAMP() AS LOAD_TIMESTAMP
    FROM GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ORDERSUMMARY
    WHERE IS_CURRENT = TRUE
    GROUP BY NAME, ORDER_DATE;

    RETURN 'Customeraggregatespend loaded successfully';
EXCEPTION
    WHEN OTHER THEN
        INSERT INTO GEN_AI_POC_SNOWFLAKECOE.SDLC_WIZARD.ERROR_LOG (PROCEDURE_NAME, ERROR_MESSAGE)
        VALUES ('LOAD_CUSTOMERAGGREGATESPEND', SQLERRM);
        RETURN OBJECT_CONSTRUCT('error', SQLERRM)::VARCHAR;
END;